name: CI

on:
  push:
    branches:
      - '*'

jobs:
  AndroidTest:
    runs-on: macos-12

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: checkout
        uses: actions/checkout@v2

      - name: Check
        run: ./gradlew check

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          script: ./gradlew connectedCheck --stacktrace

      - name: Publish test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: integration-library/build/reports
        if: ${{ failure() }}
